---
title: "Commercial vs. Residential Energy Use Impacts due to COVID-19"
author: "Samantha Liu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

## Initial Set-up
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library(knitr)
```

```{r setup-libraries}
library(shinydashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(reshape)
library(htmltools)
library(ggplot2)
library(grid)
library(formattable)
library(censusapi)

setwd("C:/Users/liusa/github/wfh-covid-analysis/PGE_analysis")

mapbox_sat <- "https://api.mapbox.com/styles/v1/samanyl/ck9hpl0sm0fuq1ip8yfb2yrn8/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1Ijoic2FtYW55bCIsImEiOiJjazlocGNvYWgxMHhxM2Rud2pxdzVnMnp2In0.D_j3K9tXiEddHH-8UUkeZQ"
mapbox_satAtt <- "© <a href='https://www.mapbox.com/map-feedback/'>Mapbox</a> Satellite Map"

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

github_rds <- "https://github.com/stanfordfuturebay/stanfordfuturebay.github.io/blob/master/data/"
bay_counties <- readRDS(gzcon(url(paste0(github_rds,"bay_counties.rds?raw=true")))) %>% 
  arrange(NAME)

# ca_zipcodes <- read.csv("C:/Users/liusa/github/covid19/snap project/sam/ca_zipcodes_city_county.csv")
# ca_zipcodes$ZIP <- as.character(ca_zipcodes$ZIP)
# ca_zipcodes %>% filter(COUNTY %in% bay_county_names) %>% saveRDS("C:/Users/liusa/github/covid19/snap project/sam/bayarea_zipcodes.rds")

bayarea_zipcodes <- readRDS("C:/Users/liusa/github/covid19/Sam_Liu/bayarea_zipcodes.rds")

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

```

```{r setup-pge-data}
# filter based on data values != na or 0
# 
# combining <- function(pattern) {
#   files <- list.files(pattern = pattern)
#   return(do.call(rbind, lapply(files,read_csv)))
# }
# 
# electric <-
#   combining("PGE_20[1-2][0-9]_Q[1-4]_ElectricUsageByZip.csv") %>%
#   filter(CUSTOMERCLASS %in% c("Elec- Residential","Elec- Commercial","Elec- Industrial"))
# 
# electric$ZIPCODE = as.character(electric$ZIPCODE)
# 
# gas <-
#   combining("PGE_20[1-2][0-9]_Q[1-4]_GasUsageByZip.csv") %>%
#   filter(CUSTOMERCLASS %in% c("Gas- Residential","Gas- Commercial"))
# 
# gas$ZIPCODE = as.character(gas$ZIPCODE)
# 
# saveRDS(electric,"electric.rds")
# saveRDS(gas,"gas.rds")
# 
# bay_zctas <- readRDS("P:/Stanford/Classes/CEE218Z - Shaping the Future of the Bay/bay_zctas.rds")

electric <- readRDS("electric.rds")
gas <- readRDS("gas.rds")

```

## Pre-Analysis (Maps)
```{r map-data, eval=TRUE}

# only analyzed between January through March of 2019 and 2020
# electric_zip <- 
#   electric %>% 
#   filter(MONTH <= 3) %>% 
#   group_by(ZIPCODE,YEAR,CUSTOMERCLASS) %>% 
#     summarize(
#     SUMKWH = sum(TOTALKWH),
#     AVGKWH = mean(AVERAGEKWH, na.rm = T)
#     )
# 
# electric_pivot_sum <- 
#   electric_zip %>%
#   cast(ZIPCODE ~ YEAR + CUSTOMERCLASS, fun.aggregate = sum, value="SUMKWH") %>% 
#   as.data.frame() %>%
#   left_join(bay_zctas,by=c("ZIPCODE"="ZCTA5CE10"))
# 
# electric_pivot <- 
#   electric_zip %>%
#   cast(ZIPCODE ~ YEAR + CUSTOMERCLASS, fun.aggregate = mean, value=c("AVGKWH")) %>% 
#   as.data.frame() %>% 
#   left_join(electric_pivot_sum,by=c("ZIPCODE"),suffix=c("_avg","_sum")) %>% 
#   st_as_sf(dim = "XY", sf_column_name = "geometry") %>% 
#   st_transform(crs=4326)
# 
# electricComm_avg2020 <- 
#   electric_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Elec- Commercial_avg` < `2020_Elec- Commercial_avg` & 
#                  !is.na(`2019_Elec- Commercial_avg`) & 
#                  !is.na(`2020_Elec- Commercial_avg`))
# 
# electricComm_avg2019 <- 
#   electric_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Elec- Commercial_avg` >= `2020_Elec- Commercial_avg` & 
#                  !is.na(`2019_Elec- Commercial_avg`) & 
#                  !is.na(`2020_Elec- Commercial_avg`) &
#                  `2019_Elec- Commercial_avg` != 0)
# 
# electricRes_avg2020 <- 
#   electric_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Elec- Residential_avg` < `2020_Elec- Residential_avg` & 
#                  !is.na(`2019_Elec- Residential_avg`) & 
#                  !is.na(`2020_Elec- Residential_avg`))
# 
# electricRes_avg2019 <- 
#   electric_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Elec- Residential_avg` >= `2020_Elec- Residential_avg` & 
#                  !is.na(`2019_Elec- Residential_avg`) & 
#                  !is.na(`2020_Elec- Residential_avg`) &
#                  `2019_Elec- Residential_avg` != 0)
# 
# saveRDS(electricComm_avg2020,"electricComm_avg2020.rds")
# saveRDS(electricComm_avg2019,"electricComm_avg2019.rds")
# saveRDS(electricRes_avg2020,"electricRes_avg2020.rds")
# saveRDS(electricRes_avg2019,"electricRes_avg2019.rds")

electricComm_avg2020 <- readRDS("electricComm_avg2020.rds")
electricComm_avg2019 <- readRDS("electricComm_avg2019.rds")
electricRes_avg2020 <- readRDS("electricRes_avg2020.rds")
electricRes_avg2019 <- readRDS("electricRes_avg2019.rds")

# gas_zip <- 
#   gas %>% 
#   filter(MONTH <= 3) %>% 
#   group_by(ZIPCODE,YEAR,CUSTOMERCLASS) %>% 
#     summarize(
#     SUMTHM = sum(TOTALTHM),
#     AVGTHM = mean(AVERAGETHM, na.rm = T)
#     ) %>% 
#   left_join(bay_zctas,by=c("ZIPCODE"="ZCTA5CE10"))
# 
# gas_pivot_sum <- 
#   gas_zip %>%
#   cast(ZIPCODE ~ YEAR + CUSTOMERCLASS, fun.aggregate = sum, value="SUMTHM") %>% 
#   as.data.frame() %>%
#   left_join(bay_zctas,by=c("ZIPCODE"="ZCTA5CE10"))
# 
# gas_pivot <- 
#   gas_zip %>%
#   cast(ZIPCODE ~ YEAR + CUSTOMERCLASS, fun.aggregate = sum, value=c("AVGTHM")) %>% 
#   as.data.frame() %>%
#   left_join(gas_pivot_sum,by=c("ZIPCODE"),suffix=c("_avg","_sum")) %>% 
#   st_as_sf(dim = "XY", sf_column_name = "geometry") %>% 
#   st_transform(crs=4326)
# 
# gasComm_avg2020 <- 
#   gas_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Gas- Commercial_avg` < `2020_Gas- Commercial_avg` & 
#                  !is.na(`2019_Gas- Commercial_avg`) & 
#                  !is.na(`2020_Gas- Commercial_avg`))
# 
# gasComm_avg2019 <- 
#   gas_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Gas- Commercial_avg` >= `2020_Gas- Commercial_avg` & 
#                  !is.na(`2019_Gas- Commercial_avg`) & 
#                  !is.na(`2020_Gas- Commercial_avg`) &
#                  `2019_Gas- Commercial_avg` != 0)
# 
# gasRes_avg2020 <- 
#   gas_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Gas- Residential_avg` < `2020_Gas- Residential_avg` & 
#                  !is.na(`2019_Gas- Residential_avg`) & 
#                  !is.na(`2020_Gas- Residential_avg`))
# 
# gasRes_avg2019 <- 
#   gas_pivot %>%
#   distinct(ZIPCODE,.keep_all = T) %>% 
#         filter(`2019_Gas- Residential_avg` >= `2020_Gas- Residential_avg` & 
#                  !is.na(`2019_Gas- Residential_avg`) & 
#                  !is.na(`2020_Gas- Residential_avg`) &
#                  `2019_Gas- Residential_avg` != 0)
# 
# saveRDS(gasComm_avg2020,"gasComm_avg2020.rds")
# saveRDS(gasComm_avg2019,"gasComm_avg2019.rds")
# saveRDS(gasRes_avg2020,"gasRes_avg2020.rds")
# saveRDS(gasRes_avg2019,"gasRes_avg2019.rds")

gasComm_avg2020 <- readRDS("gasComm_avg2020.rds")
gasComm_avg2019 <- readRDS("gasComm_avg2019.rds")
gasRes_avg2020 <- readRDS("gasRes_avg2020.rds")
gasRes_avg2019 <- readRDS("gasRes_avg2019.rds")

```

```{r electric-map, eval=TRUE}

# pal <- sequential_hcl("red-blue",n=3,rev=T)
# col <- colorNumeric(pal,domain=electric_pivot$)

elec <- leaflet() %>%
    addProviderTiles(providers$CartoDB.VoyagerLabelsUnder, group = "Default") %>%
    addTiles(urlTemplate = mapbox_sat, attribution = mapbox_satAtt, group = "Satellite") %>%
    addPolygons(
      data = electricComm_avg2020,
      # color = col(spending_brand_sum$transactions),
      color = "#5893d4",
      weight=1,
      popup = paste0(
        "<strong>",
        electricComm_avg2020$ZIPCODE,"</strong><br>2019: ",
        electricComm_avg2020$`2019_Elec- Commercial_avg`,
        " kWh<br>2020: ",
        electricComm_avg2020$`2020_Elec- Commercial_avg`,
        " kWh"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
      group = "avgElecComm_2020"
      ) %>%
    addPolygons(
      data = electricComm_avg2019,
      color = "#1f3c88",
      weight=1,
      popup = paste0(
        "<strong>",
        electricComm_avg2019$ZIPCODE,"</strong><br>2019: ",
        electricComm_avg2019$`2019_Elec- Commercial_avg`,
        " kWh<br>2020: ",
        electricComm_avg2019$`2020_Elec- Commercial_avg`,
        " kWh"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
      group = "avgElecComm_2019"
      ) %>%
    addPolygons(
      data = electricRes_avg2020,
      color = "#c1224f",
      weight=1,
      popup = paste0(
        "<strong>",
        electricRes_avg2020$ZIPCODE,"</strong><br>2019: ",
        electricRes_avg2020$`2019_Elec- Residential_avg`,
        " kWh<br>2020: ",
        electricRes_avg2020$`2020_Elec- Residential_avg`,
        " kWh"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
    group = "avgElecRes_2020"
      ) %>%
    addPolygons(
      data = electricRes_avg2019,
      color = "#f16f6f",
      weight=1,
      popup = paste0(
        "<strong>",
        electricRes_avg2019$ZIPCODE,"</strong><br>2019: ",
        electricRes_avg2019$`2019_Elec- Residential_avg`,
        " kWh<br>2020: ",
        electricRes_avg2019$`2020_Elec- Residential_avg`,
        " kWh"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
    group = "avgElecRes_2019"
      ) %>%
    # addLegend(
    #   position = 'bottomleft',
    #   values = spending_brand_sum$transactions,
    #   pal = col,
    #   title='Number of Transactions'
    #   ) %>%
    addLayersControl(
      baseGroups = c("Default","Satellite"),
      overlayGroups = c("avgElecRes_2020","avgElecComm_2020","avgElecRes_2019","avgElecComm_2019")
    ) %>%
  hideGroup(c("avgElecComm_2020","avgElecRes_2019"))

elec

```

```{r gas-map, eval=TRUE}
gs <- leaflet() %>%
    addProviderTiles(providers$CartoDB.VoyagerLabelsUnder, group = "Default") %>%
    addTiles(urlTemplate = mapbox_sat, attribution = mapbox_satAtt, group = "Satellite") %>%
    addPolygons(
      data = gasComm_avg2020,
      color = "#5893d4",
      weight=1,
      popup = paste0(
        "<strong>",
        gasComm_avg2020$ZIPCODE,"</strong><br>2019: ",
        gasComm_avg2020$`2019_Gas- Commercial_avg`,
        " THM<br>2020: ",
        gasComm_avg2020$`2020_Gas- Commercial_avg`,
        " THM"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
      group = "avgGasComm_2020"
      ) %>%
    addPolygons(
      data = gasComm_avg2019,
      # color = col(spending_brand_sum$transactions),
      color = "#1f3c88",
      weight=1,
      popup = paste0(
        "<strong>",
        gasComm_avg2019$ZIPCODE,"</strong><br>2019: ",
        gasComm_avg2019$`2019_Gas- Commercial_avg`,
        " THM<br>2020: ",
        gasComm_avg2019$`2020_Gas- Commercial_avg`,
        " THM"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
      group = "avgGasComm_2019"
      ) %>%
    addPolygons(
      data = gasRes_avg2020,
      color = "#c1224f",
      weight=1,
      popup = paste0(
        "<strong>",
        gasRes_avg2020$ZIPCODE,"</strong><br>2019: ",
        gasRes_avg2020$`2019_Gas- Residential_avg`,
        " THM<br>2020: ",
        gasRes_avg2020$`2020_Gas- Residential_avg`,
        " THM"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
    group = "avgGasRes_2020"
      ) %>%
    addPolygons(
      data = gasRes_avg2019,
      color = "#f16f6f",
      weight=1,
      popup = paste0(
        "<strong>",
        gasRes_avg2019$ZIPCODE,"</strong><br>2019: ",
        gasRes_avg2019$`2019_Gas- Residential_avg`,
        " THM<br>2020: ",
        gasRes_avg2019$`2020_Gas- Residential_avg`,
        " THM"),
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
    group = "avgGasRes_2019"
      ) %>%
    # addLegend(
    #   position = 'bottomleft',
    #   values = spending_brand_sum$transactions,
    #   pal = col,
    #   title='Number of Transactions'
    #   ) %>%
    addLayersControl(
      baseGroups = c("Default","Satellite"),
      overlayGroups = c("avgGasRes_2020","avgGasComm_2020","avgGasRes_2019","avgGasComm_2019")
    ) %>%
  hideGroup(c("avgGasComm_2020","avgGasRes_2019"))

gs

```

## 2019-2020 Energy Reductions in Usage and Costs (PG&E Electric Data)
```{r plot-comm-res-ind}

electric_Q1_comm <- 
  electric %>%
  filter(MONTH <= 3 & CUSTOMERCLASS == "Elec- Commercial") %>%   
  group_by(MONTH,YEAR,CUSTOMERCLASS) %>%
  summarize(
    SUMKWH = sum(TOTALKWH),
    AVGKWH = mean(AVERAGEKWH, na.rm = T)
    )

electric_Q1_comm_plt <- 
  ggplot(electric_Q1_comm, aes(x=MONTH, y=SUMKWH/1000000, fill=as.character(YEAR), group=YEAR)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_manual(values=c("#8ed6ff","#5893d4")) +
  labs(title="Commercial Spaces", x="Month", y="Total GWh Demand", fill="Year") +
  theme_minimal()+
  theme(legend.position = "top")

electric_Q1_ind <- 
  electric %>%
  filter(MONTH <= 3 & CUSTOMERCLASS == "Elec- Industrial") %>%  
  group_by(MONTH,YEAR,CUSTOMERCLASS) %>%
  summarize(
    SUMKWH = sum(TOTALKWH),
    AVGKWH = mean(AVERAGEKWH, na.rm = T)
    )

electric_Q1_ind_plt <- 
  ggplot(electric_Q1_ind, aes(x=MONTH, y=SUMKWH/1000000, fill=as.character(YEAR), group=YEAR)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_manual(values=c("#ffe79a","#ffa952")) +
  labs(title="Industrial Spaces", x="Month", y="Total GWh Demand", fill="Year") +
  theme_minimal()+
  theme(legend.position = "top")

electric_Q1_res <- 
  electric %>%
  filter(MONTH <= 3 & CUSTOMERCLASS == "Elec- Residential") %>%  
  group_by(MONTH,YEAR,CUSTOMERCLASS) %>%
  summarize(
    SUMKWH = sum(TOTALKWH),
    AVGKWH = mean(AVERAGEKWH, na.rm = T)
    )

electric_Q1_res_plt <- 
  ggplot(electric_Q1_res, aes(x=MONTH, y=SUMKWH/1000000, fill=as.character(YEAR), group=YEAR)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_manual(values=c("#ffaaaa","#c7004c")) +
  labs(title="Residential Spaces", x="Month", y="Total GWh Demand", fill="Year") +
  theme_minimal() +
  theme(legend.position = "top")

multiplot(electric_Q1_comm_plt, electric_Q1_ind_plt, electric_Q1_res_plt, cols=3)

```

```{r plots-differences-in-years}

electric_difference <- 
  electric %>% 
  filter(MONTH <= 3) %>%  
  group_by(MONTH,YEAR,CUSTOMERCLASS) %>%
  summarize(
    SUMKWH = sum(TOTALKWH)
    ) %>% 
  spread(YEAR, SUMKWH) %>% 
  mutate("DIFF" = (`2020` - `2019`))

electric_change_plt <- 
  ggplot(electric_difference, aes(x=MONTH,y=DIFF/`2019`,color=CUSTOMERCLASS,group=CUSTOMERCLASS)) +
  geom_line(size=1) +
  geom_point(size=1.5) +
  scale_x_continuous(breaks = seq(1, 3, by = 1)) +
  labs(title="Relative Change in Energy Consumption", x="Month", y="% Change", color="Customer Type") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values=c("#5893d4", "#ffa952", "#c7004c"), 
                    labels=c("Commercial", "Industrial", "Residential")) +
  theme_minimal() +
  theme(legend.position = "top")

electric_change_plt

```

```{r net-energy-costs-reduction}

electric_difference_costs <- read.csv("electric_difference_costs.csv")
electric_difference_costs$DIFF <- electric_difference_costs$DIFF * -1

electric_tbl <- 
  electric_difference_costs %>% 
  dplyr::select(MONTH, CUSTOMERCLASS, DIFF) %>% 
  spread(MONTH,DIFF) %>% 
  dplyr::rename("JANUARY"="1","FEBRUARY"="2", "MARCH"="3","CUSTOMER CLASS"="CUSTOMERCLASS") %>%
  formattable(align = c(rep("c")), 
              list(
              JANUARY = formatter("span",
                                        style = x ~ style(
                                          font.weight="bold",
                                          color = ifelse(x > 0, "#5b8c5a", ifelse(x < 0, "#fd5e53", "black"))
                                          )
                                        ),
              FEBRUARY = formatter("span",
                                        style = x ~ style(
                                          font.weight="bold",
                                          color = ifelse(x > 0, "#5b8c5a", ifelse(x < 0, "#fd5e53", "black"))
                                          )
                                        ),
              MARCH = formatter("span",
                                        style = x ~ style(
                                          font.weight="bold",
                                          color = ifelse(x > 0, "#5b8c5a", ifelse(x < 0, "#fd5e53", "black"))
                                          )
                                        )
              )
  )
  
electric_tbl$JANUARY <- comma(electric_tbl$JANUARY,format="d")   
electric_tbl$FEBRUARY <- comma(electric_tbl$FEBRUARY,format="d")  
electric_tbl$MARCH <- comma(electric_tbl$MARCH,format="d")  
  
electric_tbl
```

## County-Level Breakdowns
```{r energy-by-county}

# electric_zip <-
#   electric %>%
#   filter(YEAR == 2019) %>%
#   group_by(ZIPCODE) %>%
#   summarise(
#     sumkwh = sum(TOTALKWH, na.rm=T)
#   )
# 
# electric_bayarea <-
#   bayarea_zipcodes %>%
#   left_join(electric %>% filter(YEAR == 2019),by=c("ZIP"="ZIPCODE")) %>%
#   group_by(COUNTY) %>%
#   summarise(
#     SUMKWH = sum(TOTALKWH, na.rm=T)
#   )
# 
# sum(electric_bayarea$SUMKWH)/sum(electric_zip$sumkwh)

electric_bayarea <- 
  bayarea_zipcodes %>% 
  left_join(electric %>% filter(MONTH <= 3),by=c("ZIP"="ZIPCODE")) %>%
  dplyr::select(COUNTY, MONTH, YEAR, CUSTOMERCLASS, TOTALKWH,AVERAGEKWH) %>% 
  group_by(COUNTY, MONTH, CUSTOMERCLASS, YEAR) %>% 
  summarise(
    SUMKWH = sum(TOTALKWH)
  ) %>% 
  na.omit()

gas_bayarea <- 
  bayarea_zipcodes %>% 
  left_join(gas %>% filter(MONTH <= 3),by=c("ZIP"="ZIPCODE")) %>%
  dplyr::select(COUNTY, MONTH, YEAR, CUSTOMERCLASS, TOTALTHM) %>% 
  group_by(COUNTY, MONTH, CUSTOMERCLASS, YEAR) %>% 
  summarise(
    SUMTHM = sum(TOTALTHM)
  ) %>% 
  na.omit()

# total electricity demand
electric_bayarea_counties <- 
  electric_bayarea %>% 
  filter(YEAR == 2020) %>%  # filter 2019/2020 accordingly
  group_by(COUNTY, MONTH) %>% 
  summarise(
    SUMKWH = sum(SUMKWH)
  )

electric_bayarea_counties_plt <- 
  ggplot(electric_bayarea_counties, aes(x=MONTH, y=SUMKWH/1000000, fill=COUNTY, group=COUNTY)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title="2020 Electricity Demand by County", x="Month", y="Total GWh Demand", fill="County") +
  theme_minimal()

electric_bayarea_counties_plt

# commercial electricity demand
electric_comm_counties <- 
  electric_bayarea %>% 
  filter(YEAR == 2020 & CUSTOMERCLASS == "Elec- Commercial") %>%  # filter 2019/2020 accordingly
  group_by(COUNTY, MONTH) %>% 
  summarise(
    SUMKWH = sum(SUMKWH)
  )

electric_comm_counties_plt <- 
  ggplot(electric_comm_counties, aes(x=MONTH, y=SUMKWH/1000000, fill=COUNTY, group=COUNTY)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title="2020 Commercial Electricity Demand by County", x="Month", y="Total GWh Demand", fill="County") +
  theme_minimal()+
  theme(legend.position = "none")

# industrial electricity demand
electric_ind_counties <- 
  electric_bayarea %>% 
  filter(YEAR == 2020 & CUSTOMERCLASS == "Elec- Industrial") %>%  # filter 2019/2020 accordingly
  group_by(COUNTY, MONTH) %>% 
  summarise(
    SUMKWH = sum(SUMKWH)
  )

electric_ind_counties_plt <- 
  ggplot(electric_ind_counties, aes(x=MONTH, y=SUMKWH/1000000, fill=COUNTY, group=COUNTY)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title="2020 Industrial Electricity Demand by County", x="Month", y="Total GWh Demand", fill="County") +
  theme_minimal() +
  theme(legend.position = "none")

# residential electricity demand
electric_res_counties <- 
  electric_bayarea %>% 
  filter(YEAR == 2020 & CUSTOMERCLASS == "Elec- Residential") %>%  # filter 2019/2020 accordingly
  group_by(COUNTY, MONTH) %>% 
  summarise(
    SUMKWH = sum(SUMKWH)
  )

electric_res_counties_plt <- 
  ggplot(electric_res_counties, aes(x=MONTH, y=SUMKWH/1000000, fill=COUNTY, group=COUNTY)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title="2020 Residential Electricity Demand by County", x="Month", y="Total GWh Demand", fill="County") +
  theme_minimal()+
  theme(legend.position = "none")

multiplot(electric_comm_counties_plt,electric_ind_counties_plt,electric_res_counties_plt, cols=3)

```

```{r differences-by-county}
electric_bayarea_difference <- 
  electric_bayarea %>% 
  group_by(COUNTY, YEAR, MONTH) %>% # need to add CUSTOMERCLASS to incorporate costs savings below
  summarise(
    SUMKWH = sum(SUMKWH)
  ) %>% 
  spread(YEAR,SUMKWH) %>% 
  mutate("DIFF" = (`2020` - `2019`))

gas_bayarea_difference <- 
  gas_bayarea %>% 
  group_by(CUSTOMERCLASS,YEAR,MONTH) %>% # need to add CUSTOMERCLASS to incorporate costs savings below
  summarise(
    SUMTHM = sum(SUMTHM)
  ) %>% 
  spread(YEAR,SUMTHM) %>% 
  mutate("DIFF" = (`2020` - `2019`))

electric_bayarea_change_plt <- 
  ggplot(electric_bayarea_difference, aes(x=MONTH,y=DIFF/`2019`,color=COUNTY,group=COUNTY)) +
  geom_line(size=1) +
  geom_point(size=1.5) +
  scale_x_continuous(breaks = seq(1, 3, by = 1)) +
  labs(title="Relative Change in Energy Consumption by County", x="Month", y="% Change", color="County") +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal()

electric_bayarea_change_plt

```

```{r cost-savings-by-county}

electric_bayarea_difference_costs <- read.csv("electric_bayarea_difference_costs.csv")

electric_bayarea_difference_costs$DIFF <- electric_bayarea_difference_costs$DIFF * -1

electric_bayarea_tbl <- 
  electric_bayarea_difference_costs %>% 
  group_by(COUNTY, MONTH) %>%  
  summarise(
    DIFF = sum(DIFF)
  ) %>% 
  spread(MONTH, DIFF) %>% 
  dplyr::rename("JANUARY"="1","FEBRUARY"="2", "MARCH"="3") %>%
  formattable(align = c(rep("c")), 
              list(
              JANUARY = formatter("span",
                                        style = x ~ style(
                                          font.weight="bold",
                                          color = ifelse(x > 0, "#5b8c5a", ifelse(x < 0, "#fd5e53", "black"))
                                          )
                                        ),
              FEBRUARY = formatter("span",
                                        style = x ~ style(
                                          font.weight="bold",
                                          color = ifelse(x > 0, "#5b8c5a", ifelse(x < 0, "#fd5e53", "black"))
                                          )
                                        ),
              MARCH = formatter("span",
                                        style = x ~ style(
                                          font.weight="bold",
                                          color = ifelse(x > 0, "#5b8c5a", ifelse(x < 0, "#fd5e53", "black"))
                                          )
                                        )
              )
  )
  
electric_bayarea_tbl$JANUARY <- comma(electric_bayarea_tbl$JANUARY,format="d")   
electric_bayarea_tbl$FEBRUARY <- comma(electric_bayarea_tbl$FEBRUARY,format="d")  
electric_bayarea_tbl$MARCH <- comma(electric_bayarea_tbl$MARCH,format="d")  
  
electric_bayarea_tbl

```
 
## Census
```{r households}
Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

listCensusMetadata(name = "2018/acs/acs1", type = "variables")

acs <- 
  getCensus(name = "2018/acs/acs1/profile",
    vars = c("NAME","DP02_0001E","DP03_0032E","DP03_0024E","DP03_0033E","DP03_0034E","DP03_0035E","DP03_0036E","DP03_0037E",
             "DP03_0038E","DP03_0039E","DP03_0040E","DP03_0041E","DP03_0042E","DP03_0043E","DP03_0044E","DP03_0045E",
             "DP03_0062E","DP03_0051E","DP03_0025E","DP02_0015E"), 
    region = "county:*", 
    regionin = "state:06") %>% 
  filter(county %in% bay_counties$COUNTYFP) %>% 
  dplyr::rename("HH"="DP02_0001E","EMPLOYED"="DP03_0032E","WORKED FROM HOME"="DP03_0024E", "AGRICULTURE"="DP03_0033E", 
                "CONSTRUCTION"="DP03_0034E","MANUFACTURING"="DP03_0035E","WHOLESALE"="DP03_0036E","RETAIL"="DP03_0037E",
                "TRANSPORT"="DP03_0038E","INFORMATION"="DP03_0039E","FINANCE"="DP03_0040E","MANAGEMENT"="DP03_0041E",
                "EDUCATION"="DP03_0042E","ARTS"="DP03_0043E","SERVICE"="DP03_0044E","PULIC ADMIN"="DP03_0045E",
                "MEDIAN HH INCOME"="DP03_0062E","MEDIAN INCOME"="DP03_0051E","MEAN COMMUTE TIME"="DP03_0025E","AVG HH"="DP02_0015E")

write.csv(acs,"acs_raw.csv")

electric_bayarea_customers <- 
  bayarea_zipcodes %>% 
  left_join(electric %>% filter(YEAR == 2020),by=c("ZIP"="ZIPCODE")) %>%
  dplyr::select(COUNTY, MONTH, CUSTOMERCLASS, TOTALCUSTOMERS, TOTALKWH) %>% 
  group_by(MONTH, CUSTOMERCLASS) %>% 
  summarise(
    SUMKWH = sum(TOTALKWH),
    SUMCUST = sum(TOTALCUSTOMERS)
  ) %>% 
  na.omit()

write.csv(electric_bayarea_customers,"electric_bayarea_customers.csv")


gas_bayarea_customers <- 
  bayarea_zipcodes %>% 
  left_join(gas %>% filter(YEAR == 2020),by=c("ZIP"="ZIPCODE")) %>%
  dplyr::select(COUNTY,MONTH, CUSTOMERCLASS, TOTALCUSTOMERS, TOTALTHM) %>% 
  group_by(MONTH, CUSTOMERCLASS) %>% 
  summarise(
    SUMKWH = sum(TOTALTHM),
    SUMCUST = sum(TOTALCUSTOMERS)
  ) %>% 
  na.omit()

write.csv(gas_bayarea_customers,"gas_bayarea_customers.csv")

```




